In [3]:
## Vectorizarion
import numpy as np

arr = np.array([1,2,3,4,5])
result = arr ** 2  # Vectorized operation
print(result)

[ 1  4  9 16 25]


# Broadcasting 

In [4]:
result = arr + 10
print(result)

[11 12 13 14 15]


In [5]:
# Broadcasting with two arrays

arr1 = np.array([1,2,3])
arr2 = np.array([10,20,30])

retult = arr1 + arr2
print(result)

[11 12 13 14 15]


In [6]:
# Broadcasting a 2D array and a 1D array

arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([1,2,3])

result = arr1 + arr2
print(result)

[[2 4 6]
 [5 7 9]]


## Normalizing Data using broadcasting

In [8]:
data = np.array([[10, 20, 30],
                 [15, 25, 35],
                 [20, 30, 40],
                 [25, 35, 45],
                 [30, 40, 50]])

# Calculating mean and standard deviation for each feature (column)
mean = data.mean(axis=0)
std = data.std(axis=0)

#Normalizing the data using broadcasting
normalized_data = (data - mean) / std

print(normalized_data)

[[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
