In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,4,5])

In [3]:
arr

array([1, 2, 4, 5])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.full((4,6), 9)

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(0,100,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [12]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [13]:
myarr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
myarr.shape

(4, 3)

In [15]:
myarr.size

12

In [16]:
myarr.ndim

2

In [17]:
myarr.dtype

dtype('int32')

In [18]:
myarr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype = 'float32')

In [19]:
myarr.dtype

dtype('float32')

In [21]:
arra = np.array([[1,2,3], [4,5,6]])
print(arra.shape)

(2, 3)


In [23]:
reshape = arra.reshape((3,2))
print(reshape)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
falttened = arra.flatten()
print(falttened)

[1 2 3 4 5 6]


In [25]:
oned = np.array([1,2,3,4,5,6,7,8,9])


In [26]:
oned

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
oned.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])