In [1]:
import numpy as np
arr = np.array([[1,2,3], [4,5,6], [7,8,9],[10,11,12]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [6]:
flat[0]

1

In [7]:
flat[:3]

array([1, 2, 3])

In [8]:
flat[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [9]:
flat[::2]

array([ 1,  3,  5,  7,  9, 11])

In [11]:
idx = [0,2,4]
print(flat[idx])

[1 3 5]


In [12]:
arr = np.array([10,20,30,40,50])
mask = arr > 25
print(arr[mask])

[30 40 50]


In [15]:
con = np.array([1.1, 2.2, 3.3], dtype=int)

In [16]:
con

array([1, 2, 3])