In [1]:
import numpy as np
arr = np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [2]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [4]:
arr[0][1]

np.int64(2)

In [5]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

## Indexing in 3D Arrays

In [6]:
arr3D = np.array([[[1,2,3],[4,5,6]],
                  [[7,8,9],[10,11,12]]])

In [7]:
print(arr3D.shape)

(2, 2, 3)


In [8]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

### Indexing in 3D Arrays

In [9]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])

6


In [15]:
print(arr3D[:, 0, :])

[[1 2 3]
 [7 8 9]]


In [17]:
first_col = arr3D[:, :, 2]
print(first_col)

[[ 3  6]
 [ 9 12]]


In [18]:
arr3D[:, 0, :]=0

In [19]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])