In [1]:
import numpy as np

In [10]:
arr = np.array([23,3,4,5,2,1], dtype='int32')

In [11]:
arr.dtype

dtype('int32')

In [4]:
arr.astype("float64")

array([23.,  3.,  4.,  5.])

In [5]:
arr.dtype

dtype('int64')

In [12]:
arr.nbytes

24

## Downcasting to save Memory

In [13]:
arr_large = np.array([100000, 200000, 300000], dtype='int64')

In [14]:
print(arr_large)

[100000 200000 300000]


In [16]:
arr_small = arr_large.astype(np.int32)
print(arr_small)
print(arr_small.dtype)

[100000 200000 300000]
int32
