## Numpy vs. Python List - Performance Test


In [10]:
import numpy as np
import time

#Python List
size = 1_000_00
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x+y for x, y in zip(list1, list2)]
end = time.time()
print("python list addition time:", end-start)

python list addition time: 0.016184329986572266


In [4]:
# Numpy array
arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1+arr2 #Vectorizes operation
end = time.time()
print("Numpy array addition time:", end - start)

Numpy array addition time: 7.517596483230591


## Creating Numpy Array

In [7]:
import numpy as np

# Creating a 1D Numpy array
arr1 = np.array([1,2,3,4,5])
print(arr1)

# Creating a 2D Numpy array
arr2 = np.array([[1,2,3,], [4,5,6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


## Memory Efficiency - Numpy vs. Lists



In [8]:
import sys

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("Numpy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
Numpy array size: 4000 bytes


## Vectorization - No more Loops

In [11]:
# Python list (loop-bassed)
start = time.time()
list_squares = [ x**2 for x in list1]
end = time.time()
print("Total time taken by python list:", end - start)


Total time taken by python list: 2.6036181449890137


In [12]:
# Numpy (vectorization)
start = time.time()
numpy_squares = arr1 ** 2
end = time.time()
print(end-start)

0.0009953975677490234
